### ISSUE TITLE
logistic function is missing

### ISSUE THREAD

**Issue by memming** [HukLab/matRegress#3]
Please include a simple implementation. Perhaps in the `+tools` package?

**Comment by mobeets** [comment]
Added in 7be93070acd6cc3fc4e04dd1875b75f4583b9527

**Comment by memming** [comment]
7be9307 is just the MATLAB neural network toolbox wrapper. It doesn't help!

**Comment by mobeets** [comment]
Ah, I see. I saw logsim in there and assumed that would fix it.
